from pathlib import Path
p=Path('scripts/revise_audited_manuscript.py');s=p.read_text(encoding='utf-8')
s=s.replace('Camera-Derived Road Context for Physically Interpretable Trajectory Prediction: A Retrospective DonkeyCar Study','Camera-Derived Road Context for Physically Interpretable Vehicle Prediction')
s=s.replace('of the new comparisons.\n\nThe extensions','of the new comparisons. A subsequent purged temporal split includes both\nsources in training and evaluates their later segments, while retaining all\nsource-transfer results.\n\nThe extensions',1)
s=s.replace('controlled source-separated experiments distinguishing','controlled source-separated and chronological experiments distinguishing',1)
s=s.replace('The implementation adds learned lateral and heading residuals','The independently predicted curve and legacy map labels only approximate\nthese arc-length identities; the original and guarded models are structured\npredictors rather than exact physical coordinate transformations. The\nconsistent variants below explicitly address this distinction.\nThe implementation adds learned lateral and heading residuals',1)
anchor="conf=block('figure','fig:conf_environments')"
insert=r'''
if temporal_ready:
    paired=read('reports/temporal_holdout/paired_segments.json')
    improvements=paired['comparisons']['kinematic'];count=improvements['segments_total']
    results+=f'For the fixed guarded full model, seed-averaged endpoint error improves on calibrated kinematics and both Cartesian controls in all {count} eligible temporal test segments. Only {count} of the 15 assigned segments are long enough for the prescribed 15-frame context and 100-step horizon, yielding 527 windows. Full dynamics improves on shape-only in {paired["comparisons"]["guarded_shape"]["segments_improved"]} of those segments. This is descriptive paired evidence: overlapping windows and segments from two recordings do not provide {count} independent acquisition sessions.\n'
    diag=read('reports/temporal_holdout/results.json')['diagnostics']
    invalid=max(diag[f'temporal/seed{i}/guarded_full']['invalid_chart_fraction'] for i in range(3))
    results+=f'The maximum fraction of monitored full-step states with an invalid Frenet denominator in the guarded full model is {100*invalid:.4f}\\%. Finite rollouts therefore do not establish chart validity. Midpoint internal stages are not included in this monitoring.\n'
    intro=intro.replace('Numerical safeguards improve optimization behavior, but the experiments do not\nestablish a consistent accuracy advantage from curvature-dependent dynamics.',f'In a subsequent purged chronological holdout of both sources, the fixed guarded\nmodel achieves {pooled_mean("guarded_full"):.3f} m pooled endpoint error, versus {pooled_mean("kinematic"):.3f} m for calibrated\nkinematics and {pooled_mean("cartesian_road"):.3f} m for the same-input Cartesian control. These improvements\nare specific to the chronological setting; the source-transfer tests do not\nestablish a consistent advantage from curvature-dependent dynamics.')
'''
assert anchor in s;s=s.replace(anchor,insert+anchor,1)
s=s.replace('Exploratory repairs improve some numerical and\nvalidation behaviors without establishing a universal accuracy gain.','The guarded model substantially improves chronological prediction\nover matched controls, with improvements in both recordings and across all\neligible test segments against the three principal baselines. This contrast\nwith source-transfer performance identifies a useful but limited operating\nregime for the representation; geometric consistency alone is insufficient\nto establish predictive superiority.')
s=s.replace('Accuracy benefits depend on the recording, baseline, and implementation.','Accuracy benefits depend on the recording, split, baseline, and implementation.\nThe chronological-holdout gains are substantial and reproducible from saved\nweights, but the protocol was designed during development on reused sources.\nThey support within-source prediction under the stated information conditions,\nwhile the source-separated results expose limited transfer.')
p.write_text(s,encoding='utf-8')
p=Path('reports/temporal_holdout/RESULTS.md');s=p.read_text(encoding='utf-8');s=s.replace('同赛道／已覆盖工况预测实验','同赛道、两来源均参与训练的后续时间片段预测实验').replace('训练片段覆盖了两个原始记录中的工况，不能据此声称泛化到未见速度、车辆或赛道。','训练集包含两个来源，但油门仅有约 0.567 和 0.633 两档，后续仍可能出现工况变化；不能称为严格同分布验证，也不能声称泛化到未见速度、车辆或赛道。');s+='\n补充：15 个指定测试片段中，14 个能形成完整的历史及 100 步预测窗口，共 527 个窗口；过短片段不产生窗口，没有按误差删样本。此处措辞经工况审计校正，冻结实验脚本与协议未修改。\n';p.write_text(s,encoding='utf-8')
p=Path('reports/EXPERIMENT_LEDGER.md');s=p.read_text(encoding='utf-8');marker='\n第 5 轮的动机';s=s.replace(marker,'\n| 6 | coupled_road | 在第 5 轮测试前冻结：让同一曲率表示生成单位弧长道路形状，消除两个独立头的不一致 | 耦合 full/shape、原独立编码器配相同圆弧解码、同输入 Cartesian；与第 5 轮完全相同划分 |\n'+marker,1);s+='\n第 6 轮感知训练完成后进一步发现旧地图平滑后未重新弧长参数化，且曲率另行平滑，标签不满足精确一致性；只读训练／验证审计见 road_geometry/native_label_audit.json。该发现不作为撤销任何实验或选择性丢弃模型的理由。\n';p.write_text(s,encoding='utf-8')
